#!/usr/bin/bash
#must have exec perms and run as sudo
pacman -S notepadqq pcmanfm lxappearance-gtk3 breeze gnome-themes-extra ttf-dejavu ttf-liberation neofetch dmenu htop rxvt-unicode xorg-xsetroot feh ffmpeg gst-plugins-ugly gst-libav gstreamer alsa-utils gst-plugins-good pavucontrol pamixer xorg-xset audacious keepassxc nnn zathura pulseaudio ttf-font-awesome nomacs emacs
