#!/usr/bin/bash
#must have exec perms and run as root
pacman -S notepadqq pcmanfm lxappearance-gtk3 breeze gnome-themes-extra ttf-dejavu ttf-liberation neofetch dmenu htop rxvt-unicode feh ffmpeg gst-plugins-ugly gst-libav gstreamer alsa-utils gst-plugins-good pavucontrol pamixer xorg audacious keepassxc nnn zathura pulseaudio tk ttf-font-awesome nomacs
